---
# Application variables
app_name: devops-app
docker_image: your_dockerhub_username/devops-info-service
docker_tag: latest
app_port: 8000
app_internal_port: 8000

# Docker Compose
compose_project_dir: "/opt/{{ app_name }}"
docker_compose_version: "3.8"

# Wipe logic
web_app_wipe: false