apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "myapp.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "myapp.name" . }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-file.yaml") . | sha256sum }}
    spec:
      volumes:
        - name: config-volume
          configMap:
            name: {{ include "myapp.fullname" . }}-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: {{ include "myapp.fullname" . }}-data

      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.service.targetPort }}

          envFrom:
            - configMapRef:
                name: {{ include "myapp.fullname" . }}-env

          volumeMounts:
            - name: config-volume
              mountPath: /config
            - name: data-volume
              mountPath: /data

          livenessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 10
            periodSeconds: 5

          readinessProbe:
            httpGet:
              path: /
              port: {{ .Values.service.targetPort }}
            initialDelaySeconds: 5
            periodSeconds: 3